services:
  - type: web
    name: arcdrop-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ARC_RPC_URL
        value: https://rpc.testnet.arc.network
      - key: ARC_CHAIN_ID
        value: 5042002
      - key: ARC_USDC_ADDRESS
        value: 0x3600000000000000000000000000000000000000
      - key: ARC_DROP_CONTRACT
        value: ""
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
